name: Bingo # the name of the plugin.
version: 1.1.5 # the version of the plugin.
main: Main # the main class of the plugin.
author: icicl
api-version: 1.13
#load: startup
commands:
  bingo:
    description: Play bingo.
    usage: /<command> [new][join][start][map][goals]